CREATE TABLE IF NOT EXISTS generation_record (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    generation_type VARCHAR(32)  NOT NULL COMMENT 'TEXT_TO_IMAGE, IMAGE_TO_IMAGE, TEXT_TO_VIDEO, IMAGE_TO_VIDEO',
    prompt          TEXT         NOT NULL,
    style           VARCHAR(64)  NULL,
    width           INT          NULL,
    height          INT          NULL,
    ratio           VARCHAR(16)  NULL,
    duration        INT          NULL,
    resolution      VARCHAR(32)  NULL,
    storage_url     VARCHAR(512) NULL COMMENT '本地或 OSS 访问地址',
    remote_url      VARCHAR(1024) NULL COMMENT 'AI 平台原始地址',
    reference_url   VARCHAR(512) NULL COMMENT '图生图/图生视频参考图地址',
    external_task_id VARCHAR(128) NULL COMMENT 'Seedance 异步任务 ID',
    status          VARCHAR(32)  NOT NULL DEFAULT 'SUCCEEDED',
    cached          TINYINT(1)   NOT NULL DEFAULT 0,
    error_message   TEXT         NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_type_created (generation_type, created_at DESC),
    INDEX idx_external_task (external_task_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
